# Utilizing 2021 Population Data to Re-Do Computations From Paper[..]

In [1]:
import pandas as pd

In [12]:
file_path = r"C:\Users\wfeij\Downloads\Mesh Block Counts 2021.xlsx"

# Load the Excel file
xls = pd.ExcelFile(file_path)

# List to hold DataFrames for each sheet
sheet_list = []

# Iterate through each sheet and read it into a DataFrame
for sheet_name in xls.sheet_names[2:]:
    df = pd.read_excel(xls, sheet_name=sheet_name,skiprows=6)
    sheet_list.append(df)

# Concatenate all DataFrames
concatenated_df = pd.concat(sheet_list, ignore_index=True)

# concatenated_df[['MB_CODE_2021', 'MB_CATEGORY_NAME_2021', 'AREA_ALBERS_SQKM', 'Dwelling', 'Person', 'State','Geographic Extent Name']].to_pickle("new data/mb_data_2021.pkl")

In [17]:
concatenated_df.head()

,MB_CODE_2021,MB_CATEGORY_NAME_2021,AREA_ALBERS_SQKM,Dwelling,Person,State,Unnamed: 0,Unnamed: 1,Geographic Extent Name,Unnamed: 3,Unnamed: 4
0,10644310000,Education,0.0148,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN
1,10644320000,Education,0.0158,0.0,20.0,1.0,NaN,NaN,NaN,NaN,NaN
2,10644330000,Parkland,0.0054,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN
3,10644340000,Education,0.0242,0.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN
4,10644350000,Residential,0.0224,118.0,219.0,1.0,NaN,NaN,NaN,NaN,NaN